/**
 * Generates dist/geraldo-tokens.css from themes/default.json
 */
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(__dirname, '..');
const data = JSON.parse(readFileSync(join(pkgRoot, 'themes/default.json'), 'utf8'));

function emitBlock(vars) {
  return Object.entries(vars)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, v]) => `  --geraldo-${k}: ${v};`)
    .join('\n');
}

const header = `/**
 * Geraldo Design Tokens — generated from themes/default.json
 * Do not edit by hand; change the JSON and run the themes package build.
 */

`;

const css = `${header}:root {
${emitBlock(data.light)}
}

[data-geraldo-theme='dark'],
.geraldo-theme-dark {
${emitBlock(data.dark)}
}
`;

const outDir = join(pkgRoot, 'dist');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'geraldo-tokens.css'), css);

const tailwindThemePath = join(pkgRoot, 'tailwind/geraldo-theme.css');
const tailwindTheme = readFileSync(tailwindThemePath, 'utf8');
const tailwindBundle = `/**
 * Geraldo tokens + Tailwind v4 theme — generated by themes build.
 * @example
 * @import "@aiqfome-sdk/themes/tailwind.css";
 * @import "tailwindcss";
 */

@import './geraldo-tokens.css';

${tailwindTheme}
`;
writeFileSync(join(outDir, 'tailwind.css'), tailwindBundle);
